<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAWqIWxq\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAWqIWxq/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAWqIWxq.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAWqIWxq\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAWqIWxq\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'AWqIWxq',
    'container.build_id' => '416ae7f5',
    'container.build_time' => 1548693296,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerAWqIWxq');
